server {
    listen 443 ssl;
    http2 on;
    server_name www.doorpoint29.ru;

    ssl_certificate /etc/letsencrypt/live/doorpoint29.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doorpoint29.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://doorpoint29.ru$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name doorpoint29.ru;

    ssl_certificate /etc/letsencrypt/live/doorpoint29.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doorpoint29.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    client_max_body_size 10m;

    location /_next/static/ {
        alias /var/www/doorpoint/doorpoint_nextjs/.next/static/;
        expires 1y;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /uploads/ {
        alias /var/www/doorpoint/doorpoint_nextjs/public/uploads/;
        expires 30d;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
        add_header Cache-Control "public";
        access_log off;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
        proxy_connect_timeout 30s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }
}

server {
    listen 80;
    server_name doorpoint29.ru www.doorpoint29.ru;
    return 301 https://doorpoint29.ru$request_uri;
}
