server {
    listen 443 ssl;
    server_name www.doorpoint29.ru;
    ssl_certificate /etc/letsencrypt/live/doorpoint29.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doorpoint29.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    return 301 https://doorpoint29.ru$request_uri;
}

server {
    listen 443 ssl;
    server_name doorpoint29.ru;

    ssl_certificate /etc/letsencrypt/live/doorpoint29.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/doorpoint29.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_connect_timeout 30s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }
}

server {
    listen 80;
    server_name doorpoint29.ru www.doorpoint29.ru;
    return 301 https://doorpoint29.ru$request_uri;
}
